//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./recommendations_types');
//HELPER FUNCTIONS AND STRUCTURES

ItemBasedRecommendation_listItemBasedRecommendations_args = function(args) {
  this.start = null;
  this.limit = null;
  if (args) {
    if (args.start !== undefined) {
      this.start = args.start;
    }
    if (args.limit !== undefined) {
      this.limit = args.limit;
    }
  }
};
ItemBasedRecommendation_listItemBasedRecommendations_args.prototype = {};
ItemBasedRecommendation_listItemBasedRecommendations_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.start = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.limit = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ItemBasedRecommendation_listItemBasedRecommendations_args.prototype.write = function(output) {
  output.writeStructBegin('ItemBasedRecommendation_listItemBasedRecommendations_args');
  if (this.start !== null && this.start !== undefined) {
    output.writeFieldBegin('start', Thrift.Type.I32, 1);
    output.writeI32(this.start);
    output.writeFieldEnd();
  }
  if (this.limit !== null && this.limit !== undefined) {
    output.writeFieldBegin('limit', Thrift.Type.I32, 2);
    output.writeI32(this.limit);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ItemBasedRecommendation_listItemBasedRecommendations_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ItemBasedRecommendation_listItemBasedRecommendations_result.prototype = {};
ItemBasedRecommendation_listItemBasedRecommendations_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.success = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = new ttypes.UserRecommendations();
          elem14.read(input);
          this.success.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ItemBasedRecommendation_listItemBasedRecommendations_result.prototype.write = function(output) {
  output.writeStructBegin('ItemBasedRecommendation_listItemBasedRecommendations_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter15 in this.success)
    {
      if (this.success.hasOwnProperty(iter15))
      {
        iter15 = this.success[iter15];
        iter15.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ItemBasedRecommendation_findItemBasedRecommendations_args = function(args) {
  this.userCode = null;
  if (args) {
    if (args.userCode !== undefined) {
      this.userCode = args.userCode;
    }
  }
};
ItemBasedRecommendation_findItemBasedRecommendations_args.prototype = {};
ItemBasedRecommendation_findItemBasedRecommendations_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.userCode = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ItemBasedRecommendation_findItemBasedRecommendations_args.prototype.write = function(output) {
  output.writeStructBegin('ItemBasedRecommendation_findItemBasedRecommendations_args');
  if (this.userCode !== null && this.userCode !== undefined) {
    output.writeFieldBegin('userCode', Thrift.Type.STRING, 1);
    output.writeString(this.userCode);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ItemBasedRecommendation_findItemBasedRecommendations_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ItemBasedRecommendation_findItemBasedRecommendations_result.prototype = {};
ItemBasedRecommendation_findItemBasedRecommendations_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size16 = 0;
        var _rtmp320;
        this.success = [];
        var _etype19 = 0;
        _rtmp320 = input.readListBegin();
        _etype19 = _rtmp320.etype;
        _size16 = _rtmp320.size;
        for (var _i21 = 0; _i21 < _size16; ++_i21)
        {
          var elem22 = null;
          elem22 = new ttypes.Recommendation();
          elem22.read(input);
          this.success.push(elem22);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ItemBasedRecommendation_findItemBasedRecommendations_result.prototype.write = function(output) {
  output.writeStructBegin('ItemBasedRecommendation_findItemBasedRecommendations_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter23 in this.success)
    {
      if (this.success.hasOwnProperty(iter23))
      {
        iter23 = this.success[iter23];
        iter23.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ItemBasedRecommendationClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
ItemBasedRecommendationClient.prototype = {};
ItemBasedRecommendationClient.prototype.listItemBasedRecommendations = function(start, limit, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_listItemBasedRecommendations(start, limit);
};

ItemBasedRecommendationClient.prototype.send_listItemBasedRecommendations = function(start, limit) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('listItemBasedRecommendations', Thrift.MessageType.CALL, this.seqid);
  var args = new ItemBasedRecommendation_listItemBasedRecommendations_args();
  args.start = start;
  args.limit = limit;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ItemBasedRecommendationClient.prototype.recv_listItemBasedRecommendations = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ItemBasedRecommendation_listItemBasedRecommendations_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('listItemBasedRecommendations failed: unknown result');
};
ItemBasedRecommendationClient.prototype.findItemBasedRecommendations = function(userCode, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_findItemBasedRecommendations(userCode);
};

ItemBasedRecommendationClient.prototype.send_findItemBasedRecommendations = function(userCode) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('findItemBasedRecommendations', Thrift.MessageType.CALL, this.seqid);
  var args = new ItemBasedRecommendation_findItemBasedRecommendations_args();
  args.userCode = userCode;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ItemBasedRecommendationClient.prototype.recv_findItemBasedRecommendations = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ItemBasedRecommendation_findItemBasedRecommendations_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('findItemBasedRecommendations failed: unknown result');
};
ItemBasedRecommendationProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ItemBasedRecommendationProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ItemBasedRecommendationProcessor.prototype.process_listItemBasedRecommendations = function(seqid, input, output) {
  var args = new ItemBasedRecommendation_listItemBasedRecommendations_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.listItemBasedRecommendations(args.start, args.limit, function (err, result) {
    var result = new ItemBasedRecommendation_listItemBasedRecommendations_result((err != null ? err : {success: result}));
    output.writeMessageBegin("listItemBasedRecommendations", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ItemBasedRecommendationProcessor.prototype.process_findItemBasedRecommendations = function(seqid, input, output) {
  var args = new ItemBasedRecommendation_findItemBasedRecommendations_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.findItemBasedRecommendations(args.userCode, function (err, result) {
    var result = new ItemBasedRecommendation_findItemBasedRecommendations_result((err != null ? err : {success: result}));
    output.writeMessageBegin("findItemBasedRecommendations", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

