//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./recommendations_types');
//HELPER FUNCTIONS AND STRUCTURES

LasService_listUserVisitRecords_args = function(args) {
  this.start = null;
  this.limit = null;
  if (args) {
    if (args.start !== undefined) {
      this.start = args.start;
    }
    if (args.limit !== undefined) {
      this.limit = args.limit;
    }
  }
};
LasService_listUserVisitRecords_args.prototype = {};
LasService_listUserVisitRecords_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.start = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.limit = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_listUserVisitRecords_args.prototype.write = function(output) {
  output.writeStructBegin('LasService_listUserVisitRecords_args');
  if (this.start !== null && this.start !== undefined) {
    output.writeFieldBegin('start', Thrift.Type.I32, 1);
    output.writeI32(this.start);
    output.writeFieldEnd();
  }
  if (this.limit !== null && this.limit !== undefined) {
    output.writeFieldBegin('limit', Thrift.Type.I32, 2);
    output.writeI32(this.limit);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasService_listUserVisitRecords_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
LasService_listUserVisitRecords_result.prototype = {};
LasService_listUserVisitRecords_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size16 = 0;
        var _rtmp320;
        this.success = [];
        var _etype19 = 0;
        _rtmp320 = input.readListBegin();
        _etype19 = _rtmp320.etype;
        _size16 = _rtmp320.size;
        for (var _i21 = 0; _i21 < _size16; ++_i21)
        {
          var elem22 = null;
          elem22 = new ttypes.UserVisitRecord();
          elem22.read(input);
          this.success.push(elem22);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_listUserVisitRecords_result.prototype.write = function(output) {
  output.writeStructBegin('LasService_listUserVisitRecords_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter23 in this.success)
    {
      if (this.success.hasOwnProperty(iter23))
      {
        iter23 = this.success[iter23];
        iter23.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasService_findVisitRecords_args = function(args) {
  this.userCode = null;
  this.houseType = null;
  if (args) {
    if (args.userCode !== undefined) {
      this.userCode = args.userCode;
    }
    if (args.houseType !== undefined) {
      this.houseType = args.houseType;
    }
  }
};
LasService_findVisitRecords_args.prototype = {};
LasService_findVisitRecords_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.userCode = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BYTE) {
        this.houseType = input.readByte();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_findVisitRecords_args.prototype.write = function(output) {
  output.writeStructBegin('LasService_findVisitRecords_args');
  if (this.userCode !== null && this.userCode !== undefined) {
    output.writeFieldBegin('userCode', Thrift.Type.STRING, 1);
    output.writeString(this.userCode);
    output.writeFieldEnd();
  }
  if (this.houseType !== null && this.houseType !== undefined) {
    output.writeFieldBegin('houseType', Thrift.Type.BYTE, 2);
    output.writeByte(this.houseType);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasService_findVisitRecords_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
LasService_findVisitRecords_result.prototype = {};
LasService_findVisitRecords_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size24 = 0;
        var _rtmp328;
        this.success = [];
        var _etype27 = 0;
        _rtmp328 = input.readListBegin();
        _etype27 = _rtmp328.etype;
        _size24 = _rtmp328.size;
        for (var _i29 = 0; _i29 < _size24; ++_i29)
        {
          var elem30 = null;
          elem30 = new ttypes.VisitRecord();
          elem30.read(input);
          this.success.push(elem30);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_findVisitRecords_result.prototype.write = function(output) {
  output.writeStructBegin('LasService_findVisitRecords_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter31 in this.success)
    {
      if (this.success.hasOwnProperty(iter31))
      {
        iter31 = this.success[iter31];
        iter31.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasService_listItemBasedRecommendations_args = function(args) {
  this.start = null;
  this.limit = null;
  if (args) {
    if (args.start !== undefined) {
      this.start = args.start;
    }
    if (args.limit !== undefined) {
      this.limit = args.limit;
    }
  }
};
LasService_listItemBasedRecommendations_args.prototype = {};
LasService_listItemBasedRecommendations_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.start = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.limit = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_listItemBasedRecommendations_args.prototype.write = function(output) {
  output.writeStructBegin('LasService_listItemBasedRecommendations_args');
  if (this.start !== null && this.start !== undefined) {
    output.writeFieldBegin('start', Thrift.Type.I32, 1);
    output.writeI32(this.start);
    output.writeFieldEnd();
  }
  if (this.limit !== null && this.limit !== undefined) {
    output.writeFieldBegin('limit', Thrift.Type.I32, 2);
    output.writeI32(this.limit);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasService_listItemBasedRecommendations_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
LasService_listItemBasedRecommendations_result.prototype = {};
LasService_listItemBasedRecommendations_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size32 = 0;
        var _rtmp336;
        this.success = [];
        var _etype35 = 0;
        _rtmp336 = input.readListBegin();
        _etype35 = _rtmp336.etype;
        _size32 = _rtmp336.size;
        for (var _i37 = 0; _i37 < _size32; ++_i37)
        {
          var elem38 = null;
          elem38 = new ttypes.UserRecommendations();
          elem38.read(input);
          this.success.push(elem38);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_listItemBasedRecommendations_result.prototype.write = function(output) {
  output.writeStructBegin('LasService_listItemBasedRecommendations_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter39 in this.success)
    {
      if (this.success.hasOwnProperty(iter39))
      {
        iter39 = this.success[iter39];
        iter39.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasService_findItemBasedRecommendations_args = function(args) {
  this.userCode = null;
  if (args) {
    if (args.userCode !== undefined) {
      this.userCode = args.userCode;
    }
  }
};
LasService_findItemBasedRecommendations_args.prototype = {};
LasService_findItemBasedRecommendations_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.userCode = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_findItemBasedRecommendations_args.prototype.write = function(output) {
  output.writeStructBegin('LasService_findItemBasedRecommendations_args');
  if (this.userCode !== null && this.userCode !== undefined) {
    output.writeFieldBegin('userCode', Thrift.Type.STRING, 1);
    output.writeString(this.userCode);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasService_findItemBasedRecommendations_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
LasService_findItemBasedRecommendations_result.prototype = {};
LasService_findItemBasedRecommendations_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size40 = 0;
        var _rtmp344;
        this.success = [];
        var _etype43 = 0;
        _rtmp344 = input.readListBegin();
        _etype43 = _rtmp344.etype;
        _size40 = _rtmp344.size;
        for (var _i45 = 0; _i45 < _size40; ++_i45)
        {
          var elem46 = null;
          elem46 = new ttypes.Recommendation();
          elem46.read(input);
          this.success.push(elem46);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LasService_findItemBasedRecommendations_result.prototype.write = function(output) {
  output.writeStructBegin('LasService_findItemBasedRecommendations_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter47 in this.success)
    {
      if (this.success.hasOwnProperty(iter47))
      {
        iter47 = this.success[iter47];
        iter47.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LasServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
LasServiceClient.prototype = {};
LasServiceClient.prototype.listUserVisitRecords = function(start, limit, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_listUserVisitRecords(start, limit);
};

LasServiceClient.prototype.send_listUserVisitRecords = function(start, limit) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('listUserVisitRecords', Thrift.MessageType.CALL, this.seqid);
  var args = new LasService_listUserVisitRecords_args();
  args.start = start;
  args.limit = limit;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

LasServiceClient.prototype.recv_listUserVisitRecords = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new LasService_listUserVisitRecords_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('listUserVisitRecords failed: unknown result');
};
LasServiceClient.prototype.findVisitRecords = function(userCode, houseType, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_findVisitRecords(userCode, houseType);
};

LasServiceClient.prototype.send_findVisitRecords = function(userCode, houseType) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('findVisitRecords', Thrift.MessageType.CALL, this.seqid);
  var args = new LasService_findVisitRecords_args();
  args.userCode = userCode;
  args.houseType = houseType;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

LasServiceClient.prototype.recv_findVisitRecords = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new LasService_findVisitRecords_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('findVisitRecords failed: unknown result');
};
LasServiceClient.prototype.listItemBasedRecommendations = function(start, limit, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_listItemBasedRecommendations(start, limit);
};

LasServiceClient.prototype.send_listItemBasedRecommendations = function(start, limit) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('listItemBasedRecommendations', Thrift.MessageType.CALL, this.seqid);
  var args = new LasService_listItemBasedRecommendations_args();
  args.start = start;
  args.limit = limit;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

LasServiceClient.prototype.recv_listItemBasedRecommendations = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new LasService_listItemBasedRecommendations_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('listItemBasedRecommendations failed: unknown result');
};
LasServiceClient.prototype.findItemBasedRecommendations = function(userCode, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_findItemBasedRecommendations(userCode);
};

LasServiceClient.prototype.send_findItemBasedRecommendations = function(userCode) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('findItemBasedRecommendations', Thrift.MessageType.CALL, this.seqid);
  var args = new LasService_findItemBasedRecommendations_args();
  args.userCode = userCode;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

LasServiceClient.prototype.recv_findItemBasedRecommendations = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new LasService_findItemBasedRecommendations_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('findItemBasedRecommendations failed: unknown result');
};
LasServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
LasServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

LasServiceProcessor.prototype.process_listUserVisitRecords = function(seqid, input, output) {
  var args = new LasService_listUserVisitRecords_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.listUserVisitRecords(args.start, args.limit, function (err, result) {
    var result = new LasService_listUserVisitRecords_result((err != null ? err : {success: result}));
    output.writeMessageBegin("listUserVisitRecords", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

LasServiceProcessor.prototype.process_findVisitRecords = function(seqid, input, output) {
  var args = new LasService_findVisitRecords_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.findVisitRecords(args.userCode, args.houseType, function (err, result) {
    var result = new LasService_findVisitRecords_result((err != null ? err : {success: result}));
    output.writeMessageBegin("findVisitRecords", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

LasServiceProcessor.prototype.process_listItemBasedRecommendations = function(seqid, input, output) {
  var args = new LasService_listItemBasedRecommendations_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.listItemBasedRecommendations(args.start, args.limit, function (err, result) {
    var result = new LasService_listItemBasedRecommendations_result((err != null ? err : {success: result}));
    output.writeMessageBegin("listItemBasedRecommendations", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

LasServiceProcessor.prototype.process_findItemBasedRecommendations = function(seqid, input, output) {
  var args = new LasService_findItemBasedRecommendations_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.findItemBasedRecommendations(args.userCode, function (err, result) {
    var result = new LasService_findItemBasedRecommendations_result((err != null ? err : {success: result}));
    output.writeMessageBegin("findItemBasedRecommendations", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

